[package]
name = "working"
version = "0.1.0"
publish = false
authors = ["Dan Henri <djosephhenri@gmail.com>"]
edition = "2021"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

# Remove dynamic when shipping
[dependencies]
bevy = { version = "0.7", features = ["dynamic"]}
bevy-inspector-egui = "0.10"
leafwing-input-manager = "0.4.0"