[package]
name = "working"
version = "0.1.0"
publish = false
authors = ["Dan Henri <djosephhenri@gmail.com>"]
edition = "2021"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

# Remove dynamic when shipping
[dependencies]
bevy = { version = "0.8", features = ["dynamic"]}
bevy-inspector-egui = "0.12"
leafwing-input-manager = "0.5.2"
bevy_ecs_ldtk = "0.4"
parry2d = "0.10.0"
